global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "recommendations_service"
    static_configs:
      - targets: ["recommendations_service:8000"]

  - job_name: "features_service"
    static_configs:
      - targets: ["features_service:8010"]

  - job_name: "events_service"
    static_configs:
      - targets: ["events_service:8020"]
